name: Email to GitHub

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  process-emails:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Process emails
        env:
          IMAP_HOST: ${{ vars.IMAP_HOST }}
          IMAP_PORT: ${{ vars.IMAP_PORT }}
          IMAP_USER: ${{ vars.IMAP_USER }}
          IMAP_PASSWORD: ${{ secrets.IMAP_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python scripts/email_to_github.py
